### PR TITLE
add sudo to commands where required, update private key path to match documentation

### PR DESCRIPTION
**Pull request by jasmas**

### CODE REVIEW

**Comment by jasmas** [comment]
Also, virl user does not have correct permissions to /var/local/salt (mapped to images vagrant folder) unless I chmod 777 the images directory on the host. I've had to do the same in the past when working with virl and mapping folders on os x, but I'm not sure if this is the best solution or if there might be some better guest mount options.

**Comment by Snergster** [comment]
ill create and set the perms for /var/local/salt the next time i cut a box build

**Comment by jasmas** [comment]
At least for me, the permission inside the guest have no effect. They seem to be inherited somehow from the host.

**Comment by Snergster** [comment]
oh…odd…not sure since I’ve never had this issue…
if you come up with easy fix let me know

Ed

**Pull request merged**
